{"firefoxTeam": [
		{
            "contactTW": "@deimidis",
			"contactTWurl": "https://twitter.com/deimidis",
            "contactName": "Guillermo Movia",
            "contactArea": "Reps/Noticias/Difusión",
			"contactCountry": "Argentina",
			"contactEmail": "deimidis@mozilla-hispano.org",
			"contactVideoMp4": "../videos/deimidis.mp4",
			"contactVideoOgv": "../videos/deimidis.ogv",
			"contactVideoWebm": "../videos/deimidis.webm",
			"contactImg": "../videos/img/deimidis.jpg",
			"contactTitle": "Vídeo deimidis",
			"ContactDownloadLink": "http://mzl.la/101NORA",
			"ContactShareTitle" : "@deimidis te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@deimidis también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
			
		},
		{
            "contactTW": "@gioyik",
			"contactTWurl": "https://twitter.com/gioyik",
            "contactName": "Giovanny Góngora",
            "contactArea": "Labs",
			"contactCountry": "Colombia",
			"contactEmail": "gioyik@mozilla-hispano.org",
			"contactVideoMp4": "../videos/gioyik.mp4",
			"contactVideoOgv": "../videos/gioyik.ogv",
			"contactVideoWebm": "../videos/gioyik.webm",
			"contactImg": "../videos/img/gioyik.jpg",
			"contactTitle": "Vídeo gioyik",
			"ContactDownloadLink": "http://mzl.la/105IgQq",
			"ContactShareTitle" : "@gioyik te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@gioyik cuenta qué es formar parte de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@thephoenixbird",
			"contactTWurl": "https://twitter.com/thephoenixbird",
            "contactName": "Arturo Martínez",
            "contactArea": "Difusión/Reps",
			"contactCountry": "Venezuela",
			"contactEmail": "arturo@mozilla-hispano.org",
			"contactVideoMp4": "../videos/thephoenixbird.mp4",
			"contactVideoOgv": "../videos/thephoenixbird.ogv",
			"contactVideoWebm": "../videos/thephoenixbird.webm",
			"contactImg": "../videos/img/thephoenixbird.jpg",
			"contactTitle": "Vídeo thephoenixbird",
			"ContactDownloadLink": "http://mzl.la/105IlU4",
			"ContactShareTitle" : "@thephoenixbird te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@thephoenixbird también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@nukeador",
			"contactTWurl": "https://twitter.com/nukeador",
            "contactName": "Rubén Martín",
            "contactArea": "Admón. Técnica/Reps/Difusión",
			"contactCountry": "España",
			"contactEmail": "nukeador@mozilla-hispano.org",
			"contactVideoMp4": "../videos/nukeador.mp4",
			"contactVideoOgv": "../videos/nukeador.ogv",
			"contactVideoWebm": "../videos/nukeador.webm",
			"contactImg": "../videos/img/nukeador.jpg",
			"contactTitle": "Vídeo nukeador",
			"ContactDownloadLink": "http://mzl.la/101O4ju",
			"ContactShareTitle" : "@nukeador te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@nukeador también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@gpmeneses",
			"contactTWurl": "https://twitter.com/gpmeneses",
            "contactName": "Gloria Meneses",
            "contactArea": "Reps/Derechos digitales",
			"contactCountry": "Colombia",
			"contactEmail": "gpmeneses@mozilla-hispano.org",
			"contactVideoMp4": "../videos/gpmeneses.mp4",
			"contactVideoOgv": "../videos/gpmeneses.ogv",
			"contactVideoWebm": "../videos/gpmeneses.webm",
			"contactImg": "../videos/img/gpmeneses.jpg",
			"contactTitle": "Vídeo Gloria",
			"ContactDownloadLink": "http://mzl.la/105IoiR",
			"ContactShareTitle" : "@gpmeneses te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@gpmeneses también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@felipelerena",
			"contactTWurl": "https://twitter.com/felipelerena",
            "contactName": "Felipe Lerena",
            "contactArea": "Labs/Admón. Técnica",
			"contactCountry": "Argentina",
			"contactEmail": "felipe@mozilla-hispano.org",
			"contactVideoMp4": "../videos/felipelerena.mp4",
			"contactVideoOgv": "../videos/felipelerena.ogv",
			"contactVideoWebm": "../videos/felipelerena.webm",
			"contactImg": "../videos/img/felipelerena.jpg",
			"contactTitle": "Vídeo Felipe",
			"ContactDownloadLink": "http://mzl.la/105ImYi",
			"ContactShareTitle" : "@felipelerena te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@felipelerena también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@gaby2300",
			"contactTWurl": "https://twitter.com/gaby2300",
            "contactName": "Gabriela Montagu",
            "contactArea": "Control de Calidad",
			"contactCountry": "Argentina",
			"contactEmail": "gmontagu@mozilla-hispano.org",
			"contactVideoMp4": "../videos/gaby2300.mp4",
			"contactVideoOgv": "../videos/gaby2300.ogv",
			"contactVideoWebm": "../videos/gaby2300.webm",
			"contactImg": "../videos/img/gaby2300.jpg",
			"contactTitle": "Vídeo gaby2300",
			"ContactDownloadLink": "http://mzl.la/105Iqah",
			"ContactShareTitle" : "@gaby2300 te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@gaby2300 también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@leticianunz",
			"contactTWurl": "https://twitter.com/leticianunz",
            "contactName": "Leticia Núñez",
            "contactArea": "Noticias",
			"contactCountry": "España",
			"contactEmail": "leticia.nunez.nunez@gmail.com",
			"contactVideoMp4": "../videos/leticianunz.mp4",
			"contactVideoOgv": "../videos/leticianunz.ogv",
			"contactVideoWebm": "../videos/leticianunz.webm",
			"contactImg": "../videos/img/leticianunz.jpg",
			"contactTitle": "Vídeo leticianunz",
			"ContactDownloadLink": "http://mzl.la/101OaaE",
			"ContactShareTitle" : "@leticianunz te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@leticianunz también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@striptm",
			"contactTWurl": "https://twitter.com/striptm",
            "contactName": "Fernando García",
            "contactArea": "Labs/Admón. Técnica",
			"contactCountry": "España",
			"contactEmail": "striptm@mozilla-hispano.org",
			"contactVideoMp4": "../videos/fer.mp4",
			"contactVideoOgv": "../videos/fer.ogv",
			"contactVideoWebm": "../videos/fer.webm",
			"contactImg": "../videos/img/fer.png",
			"contactTitle": "Vídeo Fer",
			"ContactDownloadLink": "http://mzl.la/105IqHs",
			"ContactShareTitle" : "@striptm te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@striptm también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@bernimel",
			"contactTWurl": "https://twitter.com/bernimel",
            "contactName": "Berni Melero",
            "contactArea": "Difusión",
			"contactCountry": "España",
			"contactEmail": "bernimel@mozilla-hispano.org",
			"contactVideoMp4": "../videos/berni.mp4",
			"contactVideoOgv": "../videos/berni.ogv",
			"contactVideoWebm": "../videos/berni.webm",
			"contactImg": "../videos/img/berni.png",
			"contactTitle": "Vídeo Berni",
			"ContactDownloadLink": "http://mzl.la/105IqXW",
			"ContactShareTitle" : "@bernimel te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@bernimel también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@ggjohan",
			"contactTWurl": "https://twitter.com/ggjohan",
            "contactName": "Johan González",
            "contactArea": "Difusión",
			"contactCountry": "Venezuela",
			"contactEmail": "johan@mozilla-hispano.org",
			"contactVideoMp4": "../videos/ggjohan.mp4",
			"contactVideoOgv": "../videos/ggjohan.ogv",
			"contactVideoWebm": "../videos/ggjohan.webm",
			"contactImg": "../videos/img/ggjohan.jpg",
			"contactTitle": "Vídeo ggjohan",
			"ContactDownloadLink": "http://mzl.la/105It5X",
			"ContactShareTitle" : "@ggjohan te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@ggjohan también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@inma_610",
			"contactTWurl": "https://twitter.com/inma_610",
            "contactName": "Inma Barrios",
            "contactArea": "Localización",
			"contactCountry": "España",
			"contactEmail": "inma.barrios@mozilla-hispano.org",
			"contactVideoMp4": "../videos/inma_610.mp4",
			"contactVideoOgv": "../videos/inma_610.ogv",
			"contactVideoWebm": "../videos/inma_610.webm",
			"contactImg": "../videos/img/inma_610.jpg",
			"contactTitle": "Vídeo inma_610",
			"ContactDownloadLink": "http://mzl.la/105Is1T",
			"ContactShareTitle" : "@inma_610 te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@inma_610 también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@Breaking_Pitt",
			"contactTWurl": "https://twitter.com/Breaking_Pitt",
            "contactName": "Pedro García",
            "contactArea": "Localización/Asistencia",
			"contactCountry": "España",
			"contactEmail": "ipgarcia@mozilla-hispano.org",
			"contactVideoMp4": "../videos/Breaking_Pitt.mp4",
			"contactVideoOgv": "../videos/Breaking_Pitt.ogv",
			"contactVideoWebm": "../videos/Breaking_Pitt.webm",
			"contactImg": "../videos/img/Breaking_Pitt.jpg",
			"contactTitle": "Vídeo Breaking_Pitt",
			"ContactDownloadLink": "http://mzl.la/105IuqF",
			"ContactShareTitle" : "@Breaking_Pitt te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@Breaking_Pitt también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		},
		{
            "contactTW": "@noctuido",
			"contactTWurl": "https://twitter.com/noctuido",
            "contactName": "Antonio Álvarez",
            "contactArea": "Asistencia",
			"contactCountry": "España",
			"contactEmail": "noctuido@mozilla-hispano.org",
			"contactVideoMp4": "../videos/noctuido.mp4",
			"contactVideoOgv": "../videos/noctuido.ogv",
			"contactVideoWebm": "../videos/noctuido.webm",
			"contactImg": "../videos/img/noctuido.jpg",
			"contactTitle": "Vídeo noctuido",
			"ContactDownloadLink": "http://mzl.la/101Op5y",
			"ContactShareTitle" : "@noctuido te cuenta qué es formar parte de Firefox",
			"ContactShareMSG" : "¿Nunca te has preguntado quién hay detrás de Firefox? Conócenos en mzl.la/DetrasdeFirefox y descarga mzl.la/FirefoxparaAndroid",
			"ContactShareStatus" : "@noctuido también está detrás de Firefox. Entra en mzl.la/DetrasdeFirefox y descarga Firefox para Android en mzl.la/FirefoxparaAndroid"
		}
]}


